name: proclaim
description: An indexed table-like data type that works well with Hive boxes.
version: 4.0.1
homepage: https://github.com/moontreeapp/proclaim

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  equatable: ^2.0.5
  hive: ^2.2.3
  ordered_set: ^5.0.0
  rxdart: ^0.27.5

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
